### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by GabeSoler** [django-commons/django-debug-toolbar#2008]
Hi, I am new here and followed the installation instructions. However, there are no instructions about how to move from there, where to look for things working, or anything that could guide me to use the app. 
I imagine this is obvious to everyone, but I will need to look for a tutorial on this app, which I think defeats the purpose of documentation. 
(I know this is an amazing app and highly recommended, but it is frustrating to not get any guide after 'how to install things', and have pages of configuration when I do not know how to open the bar yet)

**Comment by tim-schilling** [comment]
Hi @GabeSoler, interestingly enough I was thinking about this this morning. Though more in the context of listing the resources that mention the toolbar.

Here are a few that I found from a quick search. I don't know how reasonable any of them are:
- https://www.youtube.com/watch?v=c5riXBYFxLk
- https://medium.com/@abdullahsohailcs/adding-django-debug-toolbar-a-step-by-step-guide-869e71e0a501
- https://www.youtube.com/watch?v=qWLk9S6mvAY

I have a workshop project that I haven't updated since Django 4.0, but it should still work well enough for you to get an understanding of how to do things: https://github.com/tim-schilling/debug-tutorial/

**Comment by GabeSoler** [comment]
Hi, thanks for the response :)
I will check the resources. Your workshop looks really complete and worth looking at in more depth.
I read a bit from the Django for professionals that also explained set up and some uses. 

Sorry I wrote a bit frustrated, but it's such an important piece in the Django ecosystem that I would love to see it more friendly for beginners.

**Comment by tim-schilling** [comment]
> Sorry I wrote a bit frustrated, but it's such an important piece in the Django ecosystem that I would love to see it more friendly for beginners.

I've been there so many times. At least you recognized that you were frustrated when you wrote it and apologized. I appreciate that :blush:.
